// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingService.DataDbContext;

#nullable disable

namespace ProcessingService.Migrations
{
    [DbContext(typeof(StationDbContext))]
    [Migration("20260916075507_FixTypoFormFactor")]
    partial class FixTypoFormFactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProcessingService.Dtos.StationInformationDto", b =>
                {
                    b.Property<string>("Station_id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lon")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Station_id");

                    b.ToTable("stationInformation");
                });

            modelBuilder.Entity("ProcessingService.Dtos.VehicleTypesDto", b =>
                {
                    b.Property<string>("Vehicle_type_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Form_factor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("propulsion_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Vehicle_type_id");

                    b.ToTable("vehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
